Build for Android
This is cross-comilation for Android
(NDK 1.5 r1) platform. Incomplete and possible not work:
Android miss exceptions, RTTI, __at_exit (?), i.e.
in any case Android has poor C++ support.

Android NDK 1.6 r1, NDK 1.5 r1

NDK 1.6 r1: android-3 and android-4

NDK 1.5 r1: android-1.5

Android NDK (as 1.6 r1 as 1.5 r1) has problem
in libthread_db (both static and dynamic):
undefined symbol.

libthread_db.so: undefined reference to `ps_pglobal_lookup'

nm -D -C ./build/platforms/android-1.5/arch-arm/usr/lib/libthread_db.so | \
  grep ps_pglobal_lookup
     U ps_pglobal_lookup

Symbol absent in any *.o, *.a, *.so shipout
in NDK, so this block link with dynamic library and
may lead to other problems.